# 개발 환경 설정
spring:
  # 데이터소스 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true

  # 개발도구 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# 서버 설정
server:
  port: ${SERVER_PORT:8080}

# Swagger 설정 
springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
    tags-sorter: alpha
    enabled: true
  api-docs:
    enabled: true

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

# 로깅 설정
logging:
  level:
    com.vroomie.car_service.domain.operation.reservation: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  backend:
    base-url: ${APP_BACKEND_BASE_URL}
  frontend:
    base-url: ${APP_FRONTEND_BASE_URL}

# 카카오 key 설정
kakao:
  rest-api:
    key: ${KAKAO_REST_API_KEY}

# 네이버 clova ocr
ncloud:
  ocr:
    url: ${NCLOUD_OCR_URL}
    secret-key: ${NCLOUD_OCR_SECRET_KEY}

# minio
minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: minioadmin
  secret-key: minioadmin
  bucket: car-images